// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  blogs_section: dynamic(() => import("./BlogsSection")),
  clients_section: dynamic(() => import("./ClientsSection")),
  contact_section: dynamic(() => import("./ContactSection")),
  counters_section: dynamic(() => import("./CountersSection")),
  cta_section: dynamic(() => import("./CtaSection")),
  details_section: dynamic(() => import("./DetailsSection")),
  features_section: dynamic(() => import("./FeaturesSection")),
  gallery_section: dynamic(() => import("./GallerySection")),
  hero_section: dynamic(() => import("./HeroSection")),
  media_section: dynamic(() => import("./MediaSection")),
  nav_links: dynamic(() => import("./NavLinks")),
  press_release_section: dynamic(() => import("./PressReleaseSection")),
  product_categories_section: dynamic(
    () => import("./ProductCategoriesSection"),
  ),
  products_section: dynamic(() => import("./ProductsSection")),
  team_section: dynamic(() => import("./TeamSection")),
  testimonials_section: dynamic(() => import("./TestimonialsSection")),
  why_us_section: dynamic(() => import("./WhyUsSection")),
};
